version: '2'
services:
  stats:
    build: .
    ports:
      - 80:80
      - 514:514
      - 514:514/udp
      - 2003:2003
      - 2004:2004
      - 2023:2023
      - 2024:2024
      - 8125:8125/udp
      - 8126:8126
    volumes:
      - ./log:/var/log/syslog/
